name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*'  # Só roda em tags que começam com "v" seguido da versão tipo v1.0.0

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'       # Pode mudar pra versão que quiser
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
